import 'package:flutter/material.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatediphone13mini1widget/generated/GeneratedlgiliVideoWidget1.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatediphone13mini1widget/generated/GeneratedRectangle1220Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatediphone13mini1widget/generated/GeneratedRectangle1201Widget1.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatediphone13mini1widget/generated/GeneratedrnekkodWidget1.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatediphone13mini1widget/generated/GeneratedTabbar2Widget8.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatediphone13mini1widget/generated/GeneratedAdsztasarm11Widget1.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatediphone13mini1widget/generated/GeneratedFutureWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatediphone13mini1widget/generated/GeneratedFuturebirasenkronoperasyonunsonucunuierirveikifarklduru.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatediphone13mini1widget/generated/GeneratedArrowleftWidget19.dart';

/* Frame iPhone 13 mini - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13mini1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 17.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 639.0,
                child: GeneratedRectangle1201Widget1(),
              ),
              Positioned(
                left: 326.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrowleftWidget19(),
              ),
              Positioned(
                left: 23.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 242.0,
                height: 45.0,
                child: GeneratedFutureWidget(),
              ),
              Positioned(
                left: 44.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 348.0,
                child:
                    GeneratedFuturebirasenkronoperasyonunsonucunuierirveikifarklduru(),
              ),
              Positioned(
                left: 39.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 147.0,
                child: GeneratedAdsztasarm11Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 463.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 22.0,
                child: GeneratedrnekkodWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.08620689655172414;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.9137931034482759,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTabbar2Widget8(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 112.0,
                top: 649.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 58.0,
                child: GeneratedRectangle1220Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.18666666666666668;

                  final double height =
                      constraints.maxHeight * 0.027093596059113302;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.41333333333333333,
                        y: constraints.maxHeight * 0.8226600985221675,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedlgiliVideoWidget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
