import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Frame Login - Giriş Bilgileri
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginGiriBilgileriWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 21.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -223.50,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width =
                          constraints.maxWidth * 0.5786666666666667;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.05333333333333334,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedTitleWidget2(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: 20.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 54.0,
                child: GeneratedButtonLargePrimaryWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 192.0,
                child: GeneratedFrame1326Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 152.0,
                child: GeneratedNavigationBar07Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5083636474609375;

                  final double height =
                      constraints.maxHeight * 0.2869458128078818;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 2.6453333333333333,
                        y: constraints.maxHeight * -0.9630541871921182,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedImage18Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
class GeneratedArrowleftWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedOnbardingHogeldinizWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 24.0,
          height: 24.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              
              children: [
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.5833333333333334;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 14.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                          constraints.maxWidth * 0.20833333333333334,
                          translateY: constraints.maxHeight * 0.5,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: 1,
                          scaleZ: 1,
                          child: GeneratedVectorWidget104())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.2916666666666667;
                    double scaleX = (constraints.maxWidth * percentWidth) / 7.0;

                    double percentHeight = 0.5833333333333334;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 14.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                          constraints.maxWidth * 0.20833333333333334,
                          translateY:
                          constraints.maxHeight * 0.20833333333333334,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget105())
                    ]);
                  }),
                )
              ]),
        ),
      ),
    );
  }
}
/* Text E- Posta
Autogenerated by FlutLab FTF Generator
  */
class GeneratedEPostaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''E- Posta''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.5,
        fontSize: 16.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 22, 28, 43),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
/* Frame Frame 1326
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1326Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 335.0,
      height: 192.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 335.0,
              height: 86.0,
              child: GeneratedInputTextFieldWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 106.0,
              right: null,
              bottom: null,
              width: 335.0,
              height: 86.0,
              child: GeneratedInputTextFieldWidget1(),
            )
          ]),
    );
  }
}
/* Text Give Access
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGiveAccessWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Giriş Yap''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.2999999523162842,
        fontSize: 16.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w600,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
/* Group Group 90
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup90Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 335.0,
      height: 54.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 335.0,
              height: 54.0,
              child: GeneratedRectangle4Widget(),
            )
          ]),
    );
  }
}
/* Group Group 90
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup90Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 335.0,
      height: 54.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 335.0,
              height: 54.0,
              child: GeneratedRectangle4Widget1(),
            )
          ]),
    );
  }
}
/* Text Şifre
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedifreWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Şifre''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.5,
        fontSize: 16.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 22, 28, 43),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
/* Rectangle image 18
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage18Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 190.63636779785156,
      height: 233.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/ecb20d4fa18061c7496f06144756007b3bc8a947.png",
          color: null,
          fit: BoxFit.cover,
          width: 190.63636779785156,
          height: 233.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
/* Frame Input / Text Field
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputTextFieldWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 335.0,
      height: 86.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 68.0,
              height: 26.0,
              child: GeneratedEPostaWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 32.0,
              right: null,
              bottom: null,
              width: 335.0,
              height: 54.0,
              child: GeneratedGroup90Widget(),
            )
          ]),
    );
  }
}
/* Frame Input / Text Field
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputTextFieldWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 335.0,
      height: 86.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 40.0,
              height: 29.0,
              child: GeneratedifreWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 32.0,
              right: null,
              bottom: null,
              width: 335.0,
              height: 54.0,
              child: GeneratedGroup90Widget1(),
            )
          ]),
    );
  }
}
/* Frame Navigation Bar / 07
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNavigationBar07Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 375.0,
      height: 152.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          
          children: [
            Positioned(
              left: 20.0,
              top: 67.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedArrowleftWidget(),
            ),
            Positioned(
              left: 20.0,
              top: 111.0,
              right: 262.0,
              bottom: null,
              width: null,
              height: 32.0,
              child: GeneratedTitletextWidget(),
            )
          ]),
    );
  }
}
/* Rectangle Rectangle 4
    Autogenerated by FlutLab FTF Generator
  */
String _email="";
String _pass="";

class GeneratedRectangle4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 335.0,
      height: 54.0,
      child: TextField(
          decoration: InputDecoration(
            border: OutlineInputBorder(),
            hintText: 'mailiniz@oua.com',
          ),
          keyboardType: TextInputType.emailAddress,
          onChanged: (value) {
            _email = value;
          }
      ),
    );
  }
}
/* Rectangle Rectangle 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle4Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 335.0,
      height: 54.0,
      child: TextField(
          decoration: InputDecoration(
            border: OutlineInputBorder(),
            hintText: '*******',
          ),
          obscureText: true,
          onChanged: (value) {
            _pass = value;
          }
      ),
    );
  }
}
/* Instance Button - Large / Primary
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtonLargePrimaryWidget extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        if (_email == 'tahir@oua.com' && _pass == '12345') {
          Navigator.pushNamed(context, '/GeneratedLibraryDerslerWidget');
        } else {
          String message = 'E-posta veya şifre yanlış.';
          print(message);
        }
      },
      child: Container(
        decoration: BoxDecoration(
          boxShadow: [
            BoxShadow(
              color: Color.fromARGB(61, 0, 0, 0),
              offset: Offset(0.0, 2.0),
              blurRadius: 2.0,
            ),
            BoxShadow(
              color: Color.fromARGB(30, 0, 0, 0),
              offset: Offset(0.0, 0.0),
              blurRadius: 2.0,
            )
          ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(12.0),
          child: Container(
            width: 335.0,
            height: 54.0,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(12.0),
            ),
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,

                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.circular(12.0),
                    child: Container(
                      color: Color.fromARGB(255, 255, 208, 55),
                    ),
                  ),
                  Positioned(
                    left: 131.0,
                    top: 16.5,
                    right: null,
                    bottom: null,
                    width: 75.0,
                    height: 23.0,
                    child: GeneratedGiveAccessWidget(),
                  )
                ]),
          ),
        ),
      ),
    );
  }
}
class GeneratedTitletextWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Giriş Yap''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.5,
        fontSize: 20.0,
        fontFamily: 'Poppins',
        fontWeight: FontWeight.w600,
        color: Color.fromARGB(255, 22, 28, 43),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}
/* Text Title
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTitleWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RichText(
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        text: const TextSpan(
          style: TextStyle(
            height: 1.2999999182564872,
            fontSize: 14.0,
            fontFamily: 'Poppins',
            fontWeight: FontWeight.w500,
            color: Color.fromARGB(255, 78, 116, 249),

            /* letterSpacing: 0.0, */
          ),
          children: [
            TextSpan(
              text: '''Hala bir hesabın yoksa ''',
            ),
            TextSpan(
              text: '''kayıt ol''',
              style: TextStyle(
                height: 1.2999999182564872,
                fontSize: 14.0,
                fontFamily: 'Poppins',
                fontWeight: FontWeight.w500,

                /* letterSpacing: 0.0, */
              ),
            )
          ],
        ));
  }
}
/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget104 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 14.0,
      height: 0.0,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          2.0,
          strokeCap: StrokeCap.round,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M14 1C14.5523 1 15 0.552285 15 0C15 -0.552285 14.5523 -1 14 -1L14 1ZM0 -1C-0.552285 -1 -1 -0.552285 -1 0C-1 0.552285 -0.552285 1 0 1L0 -1ZM14 -1L0 -1L0 1L14 1L14 -1Z')
          ..color = Color.fromARGB(255, 22, 28, 43),
      ]),
    );
  }
}
/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVectorWidget105 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.0,
      height: 14.0,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          2.0,
          strokeCap: StrokeCap.round,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M6.29289 14.7071C6.68342 15.0976 7.31658 15.0976 7.70711 14.7071C8.09763 14.3166 8.09763 13.6834 7.70711 13.2929L6.29289 14.7071ZM0 7L-0.707107 6.29289C-1.09763 6.68342 -1.09763 7.31658 -0.707107 7.70711L0 7ZM7.70711 0.707107C8.09763 0.316583 8.09763 -0.316583 7.70711 -0.707107C7.31658 -1.09763 6.68342 -1.09763 6.29289 -0.707107L7.70711 0.707107ZM7.70711 13.2929L0.707107 6.29289L-0.707107 7.70711L6.29289 14.7071L7.70711 13.2929ZM0.707107 7.70711L7.70711 0.707107L6.29289 -0.707107L-0.707107 6.29289L0.707107 7.70711Z')
          ..color = Color.fromARGB(255, 22, 28, 43),
      ]),
    );
  }
}