import 'package:flutter/material.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm3widget/generated/GeneratedAnasayfadanistediineitimiseebilirvedilersenkonubalklarn.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm3widget/generated/GeneratedWidget2.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm3widget/generated/GeneratedTabbar3Widget1.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm3widget/generated/GeneratedWidget3.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm3widget/generated/GeneratedFrame1654Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm3widget/generated/GeneratedAtlaWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm3widget/generated/GeneratedFrame1652Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm3widget/generated/GeneratedFrame1653Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm3widget/generated/GeneratedFrame1655Widget.dart';

/* Frame Onbarding - Tanıtım-3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnbardingTantm3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 128.0,
                top: 683.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 71.0,
                child: GeneratedWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 26.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 367.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width = constraints.maxWidth * 0.088;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.464,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedAtlaWidget2(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8426666666666667;

                  final double height =
                      constraints.maxHeight * 0.08251231527093596;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.11733333333333333,
                        y: constraints.maxHeight * 0.08004926108374384,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTabbar3Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 127.0,
                top: 667.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 110.0,
                child: GeneratedWidget3(),
              ),
              Positioned(
                left: 38.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 194.0,
                child:
                    GeneratedAnasayfadanistediineitimiseebilirvedilersenkonubalklarn(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.33343098958333334;

                  final double height =
                      constraints.maxHeight * 0.16634288092552146;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5191136067708333,
                        y: constraints.maxHeight * 0.3533615713636276,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame1652Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3375474243164063;

                  final double height =
                      constraints.maxHeight * 0.16159023792285637;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.17333333333333334,
                        y: constraints.maxHeight * 0.3583743842364532,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame1653Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.34166385904947916;

                  final double height =
                      constraints.maxHeight * 0.17014500660262086;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.17333333333333334,
                        y: constraints.maxHeight * 0.18321660234423107,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame1654Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.34933333333333333;

                  final double height =
                      constraints.maxHeight * 0.16502463054187191;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.52,
                        y: constraints.maxHeight * 0.18226600985221675,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFrame1655Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
