import 'package:flutter/material.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedvideoslackwidget/generated/GeneratedAnahtarkelimelerasyncawaitasenkronprogramlamavbWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedvideoslackwidget/generated/GeneratedRectangle1219Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedvideoslackwidget/generated/GeneratedImage17Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedvideoslackwidget/generated/GeneratedRectangle1218Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedvideoslackwidget/generated/GeneratedArrowleftWidget18.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedvideoslackwidget/generated/GeneratedAsynckodlama2derstehocannyazdnnaynsnyazdmfakatHayrdiyip.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedvideoslackwidget/generated/GeneratedRectangle1221Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedvideoslackwidget/generated/Generated653PMWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedvideoslackwidget/generated/GeneratedRectangle1214Widget1.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedvideoslackwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedvideoslackwidget/generated/GeneratedTabbar2Widget7.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedvideoslackwidget/generated/GeneratedIlgilivideonunadWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedvideoslackwidget/generated/Generated08_flutterWidget.dart';

/* Frame Video + Slack
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVideoSlackWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 37.0,
                child: GeneratedRectangle1219Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 207.0,
                child: GeneratedRectangle1218Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 64.0,
                child: GeneratedRectangle1221Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 501.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 31.0,
                child: GeneratedRectangle1214Widget1(),
              ),
              Positioned(
                left: 326.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrowleftWidget18(),
              ),
              Positioned(
                left: 68.0,
                top: 509.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 21.0,
                child: Generated08_flutterWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 572.0,
                right: null,
                bottom: null,
                width: 23.272727966308594,
                height: 24.0,
                child: GeneratedImage17Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.08620689655172414;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.9137931034482759,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTabbar2Widget7(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 27.0,
                top: 338.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 18.0,
                child:
                    GeneratedAnahtarkelimelerasyncawaitasenkronprogramlamavbWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 320.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 242.0,
                height: 35.0,
                child: GeneratedIlgilivideonunadWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 39.0,
                child:
                    GeneratedAsynckodlama2derstehocannyazdnnaynsnyazdmfakatHayrdiyip(),
              ),
              Positioned(
                left: 278.0,
                top: 602.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 14.0,
                child: Generated653PMWidget(),
              )
            ]),
      ),
    ));
  }
}
