import 'package:flutter/material.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardinghogeldinizwidget/generated/GeneratedEllipse193Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardinghogeldinizwidget/generated/GeneratedEllipse192Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardinghogeldinizwidget/generated/GeneratedEllipse196Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardinghogeldinizwidget/generated/GeneratedWomanwithlaptopcomputersittingfloorisolatedwhiteremoveb.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardinghogeldinizwidget/generated/GeneratedFrame1641Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardinghogeldinizwidget/generated/GeneratedEllipse195Widget.dart';

/* Frame Onbarding -  Hoşgeldiniz
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnbardingHogeldinizWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 56.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 188.0,
                child: GeneratedEllipse195Widget(),
              ),
              Positioned(
                left: -111.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 598.0,
                height: 398.0,
                child:
                    GeneratedWomanwithlaptopcomputersittingfloorisolatedwhiteremoveb(),
              ),
              Positioned(
                left: 302.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 184.0,
                height: 184.0,
                child: GeneratedEllipse192Widget(),
              ),
              Positioned(
                left: -59.0,
                top: 139.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 96.0,
                child: GeneratedEllipse193Widget(),
              ),
              Positioned(
                left: -59.0,
                top: 139.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 96.0,
                child: GeneratedEllipse196Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 761.0,
                child: GeneratedFrame1641Widget(),
              )
            ]),
      ),
    ));
  }
}
