import 'package:flutter/material.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatednotificationswidget/generated/GeneratedNavigationBar08Widget1.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatednotificationswidget/generated/GeneratedTabbar2Widget5.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatednotificationswidget/generated/GeneratedPushnotificationsrafiki1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatednotificationswidget/generated/GeneratedGroup61Widget.dart';

/* Frame Notifications
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotificationsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 113.0,
                child: GeneratedNavigationBar08Widget1(),
              ),
              Positioned(
                left: 3.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 370.0,
                child: GeneratedPushnotificationsrafiki1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 78.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 105.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width =
                          constraints.maxWidth * 0.6986666666666667;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.152,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedGroup61Widget(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.08620689655172414;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.9137931034482759,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTabbar2Widget5(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
