import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedngilizceEitimiWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedRectangle1197Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedCourseraWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedDone_round_duotoneWidget1.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedRectangle1188Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedTahirMetehanErenWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedDone_round_duotoneWidget3.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedDone_round_duotoneWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedWidget5.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedTeknikEitimWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedRectangle1192Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedRectangle1200Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedRectangle1199Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedGiriimcilikEitimiWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedTabbar3Widget2.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedDone_round_duotoneWidget2.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedProfilsayfandanilerlemenitakipedebilirtamamladndersleri.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedRectangle1194Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedIlerlemeDurumumNisanAyGrevleriWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedEllipse203Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedRectangle1196Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedRectangle1195Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedRectangle1198Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedRectangle1193Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedAtlaWidget3.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm4widget/generated/GeneratedWidget4.dart';

/* Frame Onbarding - Tanıtım-4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnbardingTantm4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 10.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 356.0,
                height: 307.0,
                child: GeneratedRectangle1198Widget(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 34.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 371.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width = constraints.maxWidth * 0.456;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.26666666666666666,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedAtlaWidget3(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: 137.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 217.0,
                height: 240.0,
                child: GeneratedRectangle1188Widget(),
              ),
              Positioned(
                left: 142.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 16.0,
                child: GeneratedRectangle1192Widget(),
              ),
              Positioned(
                left: 142.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 16.0,
                child: GeneratedRectangle1193Widget(),
              ),
              Positioned(
                left: 142.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 16.0,
                child: GeneratedRectangle1194Widget(),
              ),
              Positioned(
                left: 142.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 16.0,
                child: GeneratedRectangle1195Widget(),
              ),
              Positioned(
                left: 142.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 16.0,
                child: GeneratedRectangle1196Widget(),
              ),
              Positioned(
                left: 142.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 16.0,
                child: GeneratedRectangle1200Widget(),
              ),
              Positioned(
                left: 142.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 16.0,
                child: GeneratedRectangle1197Widget(),
              ),
              Positioned(
                left: 142.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 16.0,
                child: GeneratedRectangle1199Widget(),
              ),
              Positioned(
                left: 120.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 71.0,
                child: GeneratedWidget4(),
              ),
              Positioned(
                left: 147.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 24.0,
                child: GeneratedIlerlemeDurumumNisanAyGrevleriWidget(),
              ),
              Positioned(
                left: 152.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 13.0,
                child: GeneratedTeknikEitimWidget(),
              ),
              Positioned(
                left: 324.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedDone_round_duotoneWidget(),
              ),
              Positioned(
                left: 324.0,
                top: 327.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedDone_round_duotoneWidget1(),
              ),
              Positioned(
                left: 29.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 37.0,
                child: GeneratedTahirMetehanErenWidget(),
              ),
              Positioned(
                left: 324.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedDone_round_duotoneWidget2(),
              ),
              Positioned(
                left: 324.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedDone_round_duotoneWidget3(),
              ),
              Positioned(
                left: 152.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 16.0,
                child: GeneratedCourseraWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedEllipse203Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 13.0,
                child: GeneratedGiriimcilikEitimiWidget(),
              ),
              Positioned(
                left: 152.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 13.0,
                child: GeneratedngilizceEitimiWidget(),
              ),
              Positioned(
                left: 45.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 245.0,
                child:
                    GeneratedProfilsayfandanilerlemenitakipedebilirtamamladndersleri(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8426666666666667;

                  final double height =
                      constraints.maxHeight * 0.08251231527093596;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.11733333333333333,
                        y: constraints.maxHeight * 0.08004926108374384,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTabbar3Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 235.0,
                top: 668.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 82.0,
                child: GeneratedWidget5(),
              )
            ]),
      ),
    ));
  }
}
