import 'package:flutter/material.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedlibraryfluttersubjectswidget4/generated/GeneratedTabbar2Widget6.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedlibraryfluttersubjectswidget4/generated/GeneratedAsyncawaitWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedlibraryfluttersubjectswidget4/generated/GeneratedrnekkodWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedlibraryfluttersubjectswidget4/generated/GeneratedArrowleftWidget17.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedlibraryfluttersubjectswidget4/generated/GeneratedAsyncanahtarszcileherhangibirfonksiyonuasenkronhalegeti.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedlibraryfluttersubjectswidget4/generated/GeneratedRectangle1220Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedlibraryfluttersubjectswidget4/generated/GeneratedAdsztasarm11Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedlibraryfluttersubjectswidget4/generated/GeneratedRectangle1201Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedlibraryfluttersubjectswidget4/generated/GeneratedlgiliVideoWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedlibraryfluttersubjectswidget4/generated/GeneratedRectangle1213Widget.dart';

/* Frame Library - Flutter-Subjects
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLibraryFlutterSubjectsWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 17.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 656.0,
                child: GeneratedRectangle1201Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 242.0,
                height: 45.0,
                child: GeneratedAsyncawaitWidget(),
              ),
              Positioned(
                left: 326.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrowleftWidget17(),
              ),
              Positioned(
                left: 38.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 147.0,
                child: GeneratedAdsztasarm11Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 22.0,
                child: GeneratedrnekkodWidget(),
              ),
              Positioned(
                left: 112.0,
                top: 646.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 58.0,
                child: GeneratedRectangle1220Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 16.0,
                child: GeneratedRectangle1213Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 275.3309631347656,
                height: 253.0,
                child:
                    GeneratedAsyncanahtarszcileherhangibirfonksiyonuasenkronhalegeti(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.08620689655172414;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.9137931034482759,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTabbar2Widget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.18666666666666668;

                  final double height =
                      constraints.maxHeight * 0.027093596059113302;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.41333333333333333,
                        y: constraints.maxHeight * 0.8189655172413793,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedlgiliVideoWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
