import 'package:flutter/material.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm2widget/generated/GeneratedAtlaWidget1.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm2widget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm2widget/generated/GeneratedTabbar3Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm2widget/generated/GeneratedHerzamangncelkalmakakademidekiyenigelimeleretektklaulaa.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm2widget/generated/GeneratedWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantm2widget/generated/GeneratedPushnotificationsrafiki2Widget.dart';

/* Frame Onbarding - Tanıtım-2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnbardingTantm2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 26.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 367.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width = constraints.maxWidth * 0.088;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.464,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedAtlaWidget1(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: 119.0,
                top: 684.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 71.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 174.0,
                top: 666.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 110.0,
                child: GeneratedWidget1(),
              ),
              Positioned(
                left: 11.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 348.0,
                child: GeneratedPushnotificationsrafiki2Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 158.0,
                child:
                    GeneratedHerzamangncelkalmakakademidekiyenigelimeleretektklaulaa(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8426666666666667;

                  final double height =
                      constraints.maxHeight * 0.08251231527093596;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.11733333333333333,
                        y: constraints.maxHeight * 0.08004926108374384,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedTabbar3Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
