import 'package:flutter/material.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantmwidget/generated/GeneratedEllipse198Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantmwidget/generated/GeneratedButtonLargePrimarywithiconWidget1.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantmwidget/generated/GeneratedAtlaWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantmwidget/generated/GeneratedTitleWidget1.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantmwidget/generated/GeneratedEllipse194Widget1.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantmwidget/generated/GeneratedEllipse197Widget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantmwidget/generated/GeneratedBazenakademidezorlandnnfarkndayzKonuKtphanesisanayardme.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantmwidget/generated/GeneratedOrnamentWidget.dart';
import 'package:flutterapp/ouakonukutuphanesiapp/generatedonbardingtantmwidget/generated/GeneratedYoungsmilingstudentwomanwhitebackground__1_removebgprev.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Onbarding - Tanıtım
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnbardingTantmWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(40.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(40.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 127.0,
                top: 673.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedEllipse198Widget(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 26.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 367.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width = constraints.maxWidth * 0.088;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.464,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedAtlaWidget(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: -50.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 513.0,
                height: 580.0,
                child:
                    GeneratedYoungsmilingstudentwomanwhitebackground__1_removebgprev(),
              ),
              Positioned(
                left: 20.0,
                top: 697.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 54.0,
                child: GeneratedButtonLargePrimarywithiconWidget1(),
              ),
              Positioned(
                left: null,
                top: -100.462890625,
                right: 159.9053955078125,
                bottom: null,
                width: 476.0946044921875,
                height: 475.4486083984375,
                child: GeneratedOrnamentWidget(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 52.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -340.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width =
                          constraints.maxWidth * 0.8986666666666666;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.06933333333333333,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedTitleWidget1(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: 35.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedEllipse194Widget1(),
              ),
              Positioned(
                left: -21.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse197Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 478.0,
                child:
                    GeneratedBazenakademidezorlandnnfarkndayzKonuKtphanesisanayardme(),
              )
            ]),
      ),
    ));
  }
}
